# Workflow name
name: CI

# Define when to trigger the Workflow
on:
    push: #an event (when you put pull or merge)
        branches:
            - master
#           - second branch
jobs: #list of tasks to carry out in a work flow
    print-greeting: #name of the job
       runs-on: ubuntu-latest #what operating system that should carry out the job 
    # Define steps to execute the pipeline
    steps:
        - name: Checkout the repo # a code that checks out the repository. (-means list)
          uses: actions/checkout@v2 # this is an action to do the job of checking the respository for a work flow
        - name: Print greeting
          run: echo "Hello World!" #execute